sample-ruby-op/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :applications

  root 'applications#index'

  get  'authorization' => 'authorizations#new'
  post 'authorization' => 'authorizations#create'

  get 'jwks' => 'jwk#index'

end

sample-ruby-op/app/models/application.rb
class Application < ActiveRecord::Base
  def self.has_redirect_uri(client_id, redirect_uri)
    Application.exists?({client_id: client_id, redirect_uri: redirect_uri})
  end
end

sample-ruby-op/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def as_json(attr)

    keys = []
    attr.each do |scope|
      keys.concat self.send("#{scope.to_s}_as_keys")
    end

    keys.inject({}) do |hash, key|
      hash.merge!(
          key => self.send(key)
      )
    end
  end

  private

  def openid_as_keys
    [:sub]
  end

  def profile_as_keys
    [:name, :given_name, :family_name, :given_name_kana, :family_name_kana, :gender]
  end

  def email_as_keys
    [:email]
  end

end

sample-ruby-op/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample-ruby-op/app/controllers/applications_controller.rb
require 'securerandom'

class ApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @application.client_id = SecureRandom.hex(32)
    @application.client_secret = SecureRandom.hex(32)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :redirect_uri)
    end
end

sample-ruby-op/app/controllers/authorizations_controller.rb
# -*- coding: utf-8 -*-
class AuthorizationsController < ApplicationController

  require 'oidc/request'
  require 'oidc/response'

  before_action :authenticate_user!

  def new
    @req = OIDC::Request.new(params)
    if @req.valid?
      render :new
      return
    end

    if (params[:redirect_uri].present? &&
        Application.has_redirect_uri(params[:client_id], params[:redirect_uri]))
      redirect_to @req.error.with_fragment(params[:redirect_uri])
    else
      render json: @req.error.response
    end
  end

  # 同意画面からPOSTされる先
  def create
    res = OIDC::Response.new(params)
    res.owner = current_user

    redirect_to res.build_response
   end

end

sample-ruby-op/app/controllers/jwk_controller.rb
require 'url_safe_base64'
require 'oidc/config'

class JwkController < ApplicationController

  def index
    key = OpenSSL::PKey::RSA.new(File.read(OIDC::Config.rsa_private_key))

    jwk = {
        kty: :RSA,
        e: UrlSafeBase64.encode64(key.e.to_s(2)),
        n: UrlSafeBase64.encode64(key.n.to_s(2)),
    }

    render :json => JSON.pretty_generate(jwk)
  end
end

sample-ruby-op/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    params[:user][:sub] = subject
    super
  end

  private

  def subject
    SecureRandom.uuid
  end

  def sign_up_params
    params.require(:user).permit(:sub,
                                 :name,
                                 :given_name,
                                 :family_name,
                                 :given_name_kana,
                                 :family_name_kana,
                                 :gender,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,
                                 :given_name,
                                 :family_name,
                                 :given_name_kana,
                                 :family_name_kana,
                                 :gender,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end

end

sample-ruby-op/app/helpers/application_helper.rb
module ApplicationHelper
end

sample-ruby-op/app/helpers/applications_helper.rb
module ApplicationsHelper
end

sample-ruby-op/app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

sample-ruby-op/app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :redirect_uri %><br>
    <%= f.text_area :redirect_uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sample-ruby-op/app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

sample-ruby-op/app/views/applications/index.html.erb
<h1>Listing applications</h1>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

sample-ruby-op/app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

sample-ruby-op/app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @application.client_id %>
</p>

<p>
  <strong>Client secret:</strong>
  <%= @application.client_secret %>
</p>

<p>
  <strong>Redirect uri:</strong>
  <%= @application.redirect_uri %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

sample-ruby-op/app/views/authorizations/new.html.erb
<header class="page-header" role="banner">
    <h1>Authorize required</h1>
</header>

<main role="main">
    <p class="h4">
    </p>

    <% if @req.scopes %>
        <div>
            <p>This application will be able to:</p>

            <ul>
                <% @req.scopes.each do |scope| %>
                    <li><%= t scope, scope: [ :scopes] %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="actions">
        <%= form_tag '/authorization', method: :post do %>
            <%= hidden_field_tag :client_id, @req.client_id %>
            <%= hidden_field_tag :redirect_uri, @req.redirect_uri %>
            <%= hidden_field_tag :state, @req.state %>
            <%= hidden_field_tag :response_type, @req.response_type %>
            <%= hidden_field_tag :scope, @req.scope %>
            <%= hidden_field_tag :nonce, @req.nonce %>
            <%= submit_tag "Authorize", class: "btn btn-success btn-lg btn-block" %>
        <% end %>
    </div>
</main>

sample-ruby-op/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample Ruby OP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>